<?php include_once  APPLICATION_PATH . '/views/partials/profile_menu.phtml'; ?>
<h1>Your vulnia profile</h1>

<div class="user_profile">
    <h4><?php echo $this->translate('Username:') . ' ' . $this->user['username'];?></h4>
    <h4><?php echo $this->translate('Email account:') . ' ' . $this->user['email'];?></h4>
    <h4><?php echo $this->translate('Registered date:') . ' ' . $this->escape(date($this->translate('l dS \o\f F Y H:i:s'), strtotime($this->user['created'])));?></h4>
</div>
