<div id="footer">
    <div class="container">
        <p class="text-muted credit">Vulnia is the place where you can search and find all the software security
            vulnerabilities,
            make comments and share knowledge with experts, get daily alerts on your email based on your own keywords
            ( <a href="/search?vulnerabilities=rails">rails</a>, <a href="/search?vulnerabilities=ruby">ruby</a>, <a href="/search?vulnerabilities=php">php</a>,
            <a href="/search?vulnerabilities=tomcat">tomcat</a>, <a href="/search?vulnerabilities=wordpress">wordpress</a>,
            <a href="/search?vulnerabilities=java">java</a>, <a href="/search?vulnerabilities=adobe flash">adobe flash</a>,
            <a href="/search?vulnerabilities=xss">xss</a>,
            <a href="/search?vulnerabilities=joomla">joomla</a>, <a href="/search?vulnerabilities=oracle">oracle</a>,
            <a href="/search?vulnerabilities=cisco ios">cisco ios</a>,
            <a href="/search?vulnerabilities=scada">scada</a>, <a href="/search?vulnerabilities=ssh">ssh</a>,
            <a href="/search?vulnerabilities=android">android</a>, <a href="/search?vulnerabilities=iphone">iphone</a>).</p>
    </div>
</div>


