<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?php echo $this->metadescription ?>" >
    <link rel="shortcut icon" href="/images/favicon.png">

    <title>vulnia.com - <?php echo $this->title; ?></title>
    <link href="//fonts.googleapis.com/css?family=VT323" rel="stylesheet" type="text/css" />
    <link href="/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    <link href="/bootstrap/dist/css/sticky-footer-navbar.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "WebSite",
      "url": "https://vulnia.com/",
      "potentialAction": {
        "@type": "SearchAction",
        "target": "https://vulnia.com/search?vulnerabilities={search_term}",
        "query-input": "required name=search_term"
      }
    }
    </script>


    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-141609-24', 'auto');
      ga('send', 'pageview');

    </script>

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/bootstrap/dist/js/bootstrap.min.js"></script>
</head>
