<?php include_once("header_common.phtml"); ?>

<body>
<div id="wrap">
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">vulnia.com</a>
            </div>
            <div class="collapse navbar-collapse">
                <?php
                    if($this->ishome != true){
                        echo new Form_Search();
                    }
                    ?>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/user/login">Login</a></li>
                    <li><a href="/contact">Contact</a></li>
                </ul>

            </div>
            <!--/.nav-collapse -->
        </div>
    </div>

    <div class="container">
        <?php
        if (isset ( $this->mensajes[0]['error'] )) { ?>

        <div class="alert alert-danger">
          <?php echo  $this->mensajes[0]['error'] ?>
        </div>
        <?php }
        ?>


        <?php echo $this->layout()->content; ?>
    </div>
</div>

<?php include_once("footer_common.phtml"); ?>

</body>
</html>
