<?php include_once  APPLICATION_PATH . '/views/partials/profile_menu.phtml'; ?>

<h2> You have <?php echo $this->alerts->count() ?> alerts</h2>
<br>
<?php
foreach ($this->alerts as  $alert):
    if($alert['score'] == 0) $alert['score'] = 'any';
    echo '<div><a href="/search?vulnerabilities='.$alert['query'].'">' . $alert['query'] . '</a>
    <br>score >= '. $alert['score'] .' </div>
    <a  id="sticker_alerts" type="button"
    class="btn btn-default" href="/alert/delete/id/' . $alert['id'] . '">Delete this alert</a>';
    echo '<hr>';
endforeach;
?>


