<?php


?>

<div id="default_header_section">
    <h2><?= $this->translate('Contact form'); ?></h2>
</div>

<?php
if (isset ($this->error)) :
    ?>
    <div class="error">
        <?php echo $this->escape($this->error); ?>
    </div>

<?php endif; ?>

<div id="main">
    <div class="span-16">

        <form action="<?= $this->escape($this->form->getAction()) ?>"
              method="<?= $this->escape($this->form->getMethod()) ?>">
            <fieldset>
                <legend><?= $this->translate('Please, write your message'); ?></legend>


                <?php echo $this->form ?>

            </fieldset>
        </form>

    </div>

</div>
