<h2><?php echo $this->total_found ?>  vulnerabilities found for "<?php  echo $this->query ?>"
<?php
if($_GET['page'] > 0){
    echo ' - page ' . $_GET['page'];
}
?>
</h2>
<! -- query search seconds: <?php echo $this->query_time ?> --->
<br>
<?php
foreach ($this->paginator as  $val):
    $val = $val[0];
    echo  '<h5> <a href="https://web.nvd.nist.gov/view/vuln/detail?vulnId='.$val['ext-id'].' ">'. $val['ext-id'] .'</a></h5>' ;
    echo '<h3>' . $val['summary'] . '</h3>';
    echo '<p>' . $val['published-datetime'] . '</p><hr>';

endforeach;

echo $this->paginationControl($this->paginator,'Elastic', 'partials/paginator_search.phtml');


