<h1><?php echo $this->total_found ?>  vulnerabilities found for "<?php  echo $this->query ?>"
<?php
if( isset($this->score) && $this->score > 0){
    echo ' with score >= ' . $this->score;
}
if( isset($this->page) && $this->page > 1){
    echo ' (page ' . $this->page . ')';
}
?>
</h1>
<! -- query search seconds: <?php echo $this->query_time ?> --->
<br>
          <?php echo
       '<a id="sticker_alerts" type="button" class="btn btn-default btn-lg" href="/alert/create">
          <span class="glyphicon glyphicon-bell"></span> Click here if you want to receive <b>'.$this->query.'</b> security email alerts.
          </a><br><br>';
?>
<?php
foreach ($this->paginator as  $val):
    if($val['score'] == null){
        $val['score'] = 'pending';
        $score_str = 'default';
    }
    else if($val['score'] < 4 && $val['score'] != null ){
        $score_str = 'info';
    }
    else if($val['score'] < 7 ){
        $score_str = 'warning';
    }
    else if($val['score'] > 6 ){
        $score_str = 'danger';
    }

    $val['summary'] = str_ireplace($this->query, '<b>'. $this->query  .'</b>', $val['summary']);
    echo '<div>published date:' . $val['published-datetime'] . '</div>';
    echo '<a href="/vulnerability?id=' . $val['id'] . ' ">' ;
    echo '<h3>' . $val['summary'] . '</h3></a>';
    echo '<span class="label label-'.$score_str.'">score: ' . $val['score'] . '</span>';
    echo '<hr>';
endforeach;

echo $this->paginationControl($this->paginator,'Elastic', 'partials/paginator_search.phtml');

?>

<script>
  $(document).ready(function(){
    $("#sticker_alerts").sticky({topSpacing:45});
  });
</script>
