<h2><?php echo $this->total_found ?>  vulnerabilities found for "<?php  echo $this->query ?>"
<?php
if( isset($_GET['page']) && $_GET['page'] > 0){
    echo ' - page ' . $_GET['page'];
}
?>
</h2>
<! -- query search seconds: <?php echo $this->query_time ?> --->
<br>
<?php
foreach ($this->paginator as  $val):
    //$val = $val[0];

    $val['summary'] = str_ireplace($this->query, '<b>'. $this->query  .'</b>', $val['summary']);
    echo '<div>published date:' . $val['published-datetime'] . '</div>';
    echo '<a href="/vulnerability?id=' . $val['id'] . ' ">' ;
    echo '<h3>' . $val['summary'] . '</h3></a>';
    echo '<hr>';


endforeach;

echo $this->paginationControl($this->paginator,'Elastic', 'partials/paginator_search.phtml');


