<div class="jumbotron">
    <div class="container">
        <ol>
            <li>Search the latest vulnerabilities about technologies you use daily.</li>
            <li>Receive on your email early alerts.</li>
            <li>Expect the bad boys</li>
        </ol>
    <?php echo new Form_Search(); ?>
    </div>
</div>




<h3>Last indexed vulnerabilities:</h3>
<?php

function truncate($string, $width, $etc = ' ..')
{
        $wrapped = explode('$trun$', wordwrap($string, $width, '$trun$', false), 2);
            return $wrapped[0] . (isset($wrapped[1]) ? $etc : '');
}

foreach ($this->paginator as $val):
    echo '<a href="/vulnerability?id=' . $val['id'] . ' ">' ;
    echo '<h3>' . $val['ext-id'] . ' - '  . truncate( $val['summary'], 90 ) . '</h3></a>';
    echo '<p>' . $val['published-datetime'] . '</p><hr>';

endforeach;

echo $this->paginationControl($this->paginator, 'Elastic', 'partials/paginator.phtml');


