<div class="jumbotron">
        Schedule security email alerts about technologies you use daily.
    <div class="container" ><?php echo new Form_Search(); ?></div>
</div>


<h3>Last indexed vulnerabilities ( <?php echo $this->lastIndexed ?> UTC+1 ) </h3>
<?php

function truncate($string, $width, $etc = ' ..')
{
        $wrapped = explode('$trun$', wordwrap($string, $width, '$trun$', false), 2);
            return $wrapped[0] . (isset($wrapped[1]) ? $etc : '');
}

foreach ($this->paginator as $val):
    if($val['score'] == null){
        $val['score'] = 'pending';
        $score_str = 'default';
    }
    else if($val['score'] < 4 && $val['score'] != null ){
        $score_str = 'info';
    }
    else if($val['score'] < 7 ){
        $score_str = 'warning';
    }
    else if($val['score'] > 6 ){
        $score_str = 'danger';
    }

    echo '<a href="/vulnerability?id=' . $val['id'] . ' ">' ;
    echo '<h3>' . $val['ext-id'] . ' - '  . truncate( $val['summary'], 170 ) . '</h3></a>';
    echo '<p>' . $val['published-datetime'] . '</p>';
    echo '<span class="label label-'.$score_str.'">score: ' . $val['score'] . '</span>';
    echo '<hr>';

endforeach;

echo $this->paginationControl($this->paginator, 'Elastic', 'partials/paginator.phtml');


